### ISSUE TITLE
Instance variable access OK in some circumstance

### ISSUE THREAD

**Issue by lewispb** [cookpad/global-style-guides#124]
Should we [update the guide](https://github.com/cookpad/global-style-guides/tree/master/ruby#prefer-method-invocation) based on https://github.com/cookpad/global-web/pull/12615#discussion_r282444010?

We allow this:

```rb
 def placeholder? 
   !!@placeholder 
end 
```

**Comment by davidstosik** [comment]
The rule:
> Prefer method invocation over instance variables

The example:
```rb
## Bad
class MarkRecipe
  def initialize(recipe)
    @recipe = recipe
  end

  def run
    @recipe.mark
  end
end

## Good
class MarkRecipe
  def initialize(recipe)
    @recipe = recipe
  end

  def run
    recipe.mark
  end

  private

    attr_reader :recipe
end
```

The exception to discuss here:
```rb
## Bad
class DoSomethingService < BaseService
  def initialize(dry_run = true)
    @dry_run = dry_run
  end

  def run
    do_something unless @dry_run
  end
end

## Acceptable?
class DoSomethingService < BaseService
  def initialize(dry_run = true)
    @dry_run = dry_run
  end

  def run
    do_something unless dry_run?
  end

  private

    def dry_run?
      !!@dry_run
    end
end

## Better or not?
class DoSomethingService < BaseService
  def initialize(dry_run = true)
    @dry_run = dry_run
  end

  def run
    do_something unless dry_run?
  end

  private

    attr_reader :dry_run

    def dry_run?
      !!dry_run
    end
end
```
I personally feel like this is actually not an exception, and it follows the rule as well. Let me explain. The rule states that we should use method invocation over instance variable, and that what the code above does when it prefers `unless dry_run?` to `unless @dry_run`. The problem is that the eyes next land on the `dry_run?` method's definition, and find this `@dry_run` instance variable, which seems to be breaking our rule. I would personally argue that it is almost equivalent to writing `attr_reader :dry_run`, as this is equivalent to defining an accessor:
```rb
# Defining an attribute reader
attr_reader :dry_run

# Is equivalent to defining the method accessor:
def dry_run
  @dry_run
end

# And so should be this "boolean variant"?
def dry_run?
  !!@dry_run
end
```

**Comment by balvig** [comment]
Just for context, here are the original reasons for the guideline: https://github.com/cookpad/global-style-guides/pull/26


I think I agree with @davidstosik that the boolean example is ok and, depending on how you interpret it, already follows the rule. 

Since however the guidelines are all about removing surprises/discussion, it might indeed be a good idea to mention that as one of the examples as well 👍, f.ex maybe tacking on:

```rb
## Also acceptable
class Image
  def initialize(placeholder: false)
    @placeholder = placeholder
  end

  def render
    if placeholder?
      # ...
    end
  end

  private
    
    def placeholder?
      !!@placeholder
    end
end
```
