### ISSUE TITLE
Revisit or clarify `Avoid using context in specs` rule  

### ISSUE THREAD

**Issue by mshka** [cookpad/global-style-guides#132]
Related thread: https://github.com/cookpad/global-web/pull/13430/files#r301483447

While writing specs for a feature, I used a `before do ... end` to setup feature toggles and freeze time 

https://github.com/cookpad/global-web/blob/110a2ec4ecc0ac81246dfbcb1633e761d7984d23/spec/events/avro/opened_contest_event_spec.rb#L5-L8

All the cases inside this spec file will test an event that is gonna be sent only if the feature toggle is enabled also in order to be tested properly we need to freeze time in each case

even though, the rules in our guide insist on not using context while writing specs https://github.com/cookpad/global-style-guides/tree/master/rspec#avoid-using-context
there are quite a few places where context is used in our project

as mentioned in the thread above:

I remember that 
>when we first wrote this guide it was based on this https://global.g.cookpad.com/qihuan-piao/20160512/171541#Good%20use%20case%20for%20let where it's stated that there is always a good use for contexts

however, the rule does not state that, can we please clarify this?

cc: @dannyd4315 

@cookpad/web-chapter what do you think?

**Comment by balvig** [comment]
Woo! A chance to rant about RSpec! 
@mshka you're being too kind. 😄 

Thanks for bringing it up though, looks like a good opportunity to clarify.

I believe you're touching on three different features of RSpec (don't you love how there is _so much stuff_ in this testing framework? 🤔)

- `before`
- `context`
- `let`

Our guides specifically say:

> - [Avoid using `context`](https://github.com/cookpad/global-style-guides/tree/master/rspec#avoid-using-context)
> - [Avoid using `let`](https://github.com/cookpad/global-style-guides/tree/master/rspec#avoid-using-let)

We should revisit and update the reasons for those rules, but note that nowhere does it say _not to use `before`_.

I think there are many valid examples of having a setup block. 

One really common one being enabling a feature toggle in a spec that is _exclusively about testing that feature_, ie:

```rb
feature "Guest sees foreign language suggestion" do
  before do
    enable_feature(:language_suggestor)
  end

  scenario ... end
  scenario ... end
  scenario ... end
end
```


...which is pretty much exactly what you have? 😄 

So, as far as I can tell, there aren't any potential problems with the specific case referenced.

The inclusion of `freeze_time` _could_ perhaps be debated?

The two existing specs make use of it, but maybe we want to test an edge case next where the time is something different/specific? We would have to either override the setup (could get confusing) or move it out. 

I think making that decision could also be deferred to later though?

---

To be honest, for all things like this, I believe a good rule of thumb is "What Would Minitest Do?" 😅 

Even `Minitest` has a `setup` block, and I see no reason to ban it outright.

In fact, I would encourage everyone to read https://guides.rubyonrails.org/testing.html. 📖 

Even if you've been writing tests for years, it's actually really great as a refresher of the basics, and _maybe_ even RSpec diehards will come away appreciating how much `Minitest` resembles "normal ruby code" and classes (because that's what it is!)

Yes, I appreciate it's an "interesting" situation to be in using `RSpec`, while looking to `Minitest` for good design practices. 😅 

...and yes, I would rewrite everything using `Minitest` tomorrow given the opportunity! 😅

**Comment by firewalker06** [comment]
I understand that sometimes we question ourselves about the reason a guide was made. Especially when its been a while since the guide was placed or when we are new to the team adjusting to new culture. 

What do you think of putting the reasoning behind the decision in the guide as well? In details tag like this:

<details>
<summary>Reason behind</summary>
It is easy to lost some `context` when there are many examples. In most cases we spent times to go back and forth just to understand a certain example. Especially if there are multiple `context` included.
</details>

**Comment by firewalker06** [comment]
@mshka @balvig ah, just a reminder, it seems  we are crossing the public-private repository boundary here. 😅 (Seeing that we use private repo and internal blogpost as reference)

Let's move this into private repository for further discussion.

**Comment by balvig** [comment]
@firewalker06 good point, I think @ChrisBr's suggestion in https://github.com/cookpad/global-style-guides/pull/127 was a good idea. 

I realize this relies on having a link somewhere, but maybe that could prod us to writing up a small blog post 😉
