### ISSUE TITLE
Testing, it vs example

### ISSUE THREAD

**Issue by lewispb** [cookpad/global-style-guides#94]
Which do we prefer and why and in which situation?

1) `it "Includes the latest comment from the recipe author" do`

2) `it "includes the latest comment from the recipe author" do`

3) `example "Includes the latest comment from the recipe author" do`

**Comment by balvig** [comment]
Aha, yes!

I think what's maybe missing here is proper documentation of how to use the new `/docs` API style that was pioneered during Bristol Camp as part of an ["API excursion"](https://github.com/cookpad/global-web/issues/7148) by @karlentwistle and @l15n, and how that affects existing API tests.

I've kinda been half [cajoling poor @karlentwistle into taking on that task](https://github.com/cookpad/global-web/issues/7396#issuecomment-387919530), no wonder he needed a holiday 😉 😅 🙇 

Incidentally this is one of those things I don't like about RSpec, why are there 100 different ways of wrapping a test (`it`, `specify`, `example`, `scenario`, etc...) , they are just all tests 😅 

I've seen people forget what kind of test they are writing and mixing `it` with `scenario` etc, and I don't blame them! 🤔 

To be honest I'm not sure there is that much value to using a different word depending on the context, except that due to the options available, using one over the other can make writing the description a bit awkward (I wish it was all just `test "..."`!).

As for `it` vs `example`, I think the convention we were arriving at was something like:

- For API documentation in `/docs`, use `example "...", document :true`
- For "raw specs" in `/api/requests`, use `it "..."`

The reason it's currently jumbled up I think is simply a matter of no one having had time to follow through on the [homework from the camp](https://github.com/cookpad/global-web/issues/7148#issuecomment-374286891) yet!

**Comment by sebasoga** [comment]
@balvig I'm glad to pick this up. I'll open a PR with some sort of suggestion.

**Comment by sebasoga** [comment]
@lewispb I think we addressed this concern in https://github.com/cookpad/global-web/pull/8447. Do you think this issue could be closed?

**Comment by lewispb** [comment]
Ok @sebasoga those inline guides look nice. Thank you.
